version: '2'
services:
  myjavaapp:
    build: .
    stdin_open: true
    tty: true
    links:
      - rabbitmq
      - rabbitmq:rabbitmq.cloud66.local
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 8080:15672 